### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by roccomuso** [GoogleChrome/push-notifications#1]
I think there's a typo in this code example:

    3. Register and install a Service Worker.

https://developers.google.com/web/fundamentals/getting-started/push-notifications/step-03?hl=en#register-and-install-a-service-worker

the folder structure suggests that the path should be: <code>./sw.js</code> and not <code>/sw.js</code>

**Comment by samdutton** [comment]
Ah — yes. I fixed this here, but it hasn't been published yet: 

https://github.com/google/WebFundamentals/issues/2445

Thanks for reporting!
