### ISSUE TITLE
Formatting issue on walkthrough

### ISSUE THREAD

**Issue by Bostwickenator** [GoogleChrome/push-notifications#11]
Under the section listed below there is a block of code that is not formatted in the code example style.

https://developers.google.com/web/fundamentals/getting-started/codelabs/push-notifications/?hl=en#subscribe_to_push_notifications

**Comment by gauntface** [comment]
This will be fixed in the next version of the codelab. Thank you for raising the issue: https://github.com/google/WebFundamentals/pull/3841
