### ISSUE TITLE
Push Notification Tutorial Mistake

### ISSUE THREAD

**Issue by KatsutoshiRF** [GoogleChrome/push-notifications#14]
On the push notification tutorial (https://developers.google.com/web/fundamentals/getting-started/codelabs/push-notifications/) when you copy the last part of the subscription endpoint URL, you should copy everything after the "send/". In general i enjoyed the tutorial.

**Comment by zetay** [comment]
I found the same error, cost me a lot of time to fix it

**Comment by itsclarke** [comment]
THIS. Thank you, this was causing me much frustration.

**Comment by gauntface** [comment]
I've started work on updating this code lab so will hopefully have it fixed
soon xx
