### ISSUE TITLE
How to send payload 

### ISSUE THREAD

**Issue by pavankumarkatakam** [GoogleChrome/push-notifications#2]
Im sending the some JSON data as payload to GCM, but how to receive here the payload on event PUSH.

**Comment by samdutton** [comment]
Payloads aren't yet supported by Push Notifications — for reasons and workarounds, take a look at the StackOverflow thread [here](http://stackoverflow.com/questions/30335749/sending-data-payload-to-the-google-chrome-push-notification-with-javascript).

NB bug to support payloads [here](https://code.google.com/p/chromium/issues/detail?id=486040).

**Comment by gauntface** [comment]
Further update, payloads require encryption: https://developers.google.com/web/updates/2016/03/web-push-encryption

In the next version of this codelab there is a companion web site that will handle this and trigger a push for you (https://github.com/google/WebFundamentals/pull/3841).

If you want to encrypt data on your own server checkout the available libraries here: https://github.com/web-push-libs/
