### ISSUE TITLE
Typos in Step 8

### ISSUE THREAD

**Issue by cloverharvest** [GoogleChrome/push-notifications#22]
1) First sentence => Missing the word "of" in this sentence:

If you click on one `of` these notifications you'll notice nothing happens.

2) Try it out Section => Delete unneeded word "this"

Try triggering a push message in DevTools again and this click on the notification. 

Correction:

Try triggering a push message in DevTools again and click on the notification.

**Comment by gauntface** [comment]
Thanks for raising the issues and giving the helpful feedback :)

Just made the changes in the google doc that the codelab is generated from, should make it's way to sources soon.
