### ISSUE TITLE
Incorrect Preview of screenshots

### ISSUE THREAD

**Issue by anujduggal88** [GoogleChrome/push-notifications#24]
# Incorrect Preview of screenshots

### Issue:
The following screenshot indicates the developer to navigate to localhost:8887. The developer is not able to run the application with this URL:

<img width="1437" alt="screen shot 2016-11-29 at 10 54 15 am" src="https://cloud.githubusercontent.com/assets/5246562/20701103/194b799c-b637-11e6-8cad-02532dc24737.png">

### Solution:
The developer needs to navigate to *localhost:8887/app/* to run the application and see the changes made in the code.
 
<img width="1426" alt="screen shot 2016-11-29 at 11 29 50 am" src="https://cloud.githubusercontent.com/assets/5246562/20701166/7a96f6f4-b637-11e6-9b37-932a62886ca7.png">

**Comment by gauntface** [comment]
The codelab does say to set up up the 200 OK extension to point at app.

> Click the choose folder button, and select the app folder.

**Comment by anujduggal88** [comment]
@gauntface : But the screenshot is non-consistent with the codelab. The folder structure in the codelab is not the same as in screenshot - it misguides the developers, don't you think so?

**Comment by gauntface** [comment]
If you set the root of the server to 'app' the screenshot is correct.
