### ISSUE TITLE
Unify push notification UX guidelines

### ISSUE THREAD

**Issue by dandv** [GoogleChrome/push-notifications#29]
We have two documents on good push notification UX:

[What Makes a Good Notification?](https://developers.google.com/web/fundamentals/engage-and-retain/push-notifications/good-notification) on Web Fundamentals
and
[Best Practices for Push Notifications Permissions UX](https://docs.google.com/document/d/1WNPIS_2F0eyDm5SS2E6LZ_75tk6XtBSnR1xNjWJ_DPE/edit) (strangely, a Google Doc)

Would it make sense to bring the latter under /web and/or merge it into the former?

CC @owencm, @jpmedley

**Comment by gauntface** [comment]
Moved to Web fundamentals: https://github.com/google/WebFundamentals/issues/4034
