### ISSUE TITLE
Notification failed on Chrome Android 

### ISSUE THREAD

**Issue by jflefebvre06** [GoogleChrome/push-notifications#3]
We have juste implemented chrome push notifications following your sample and it works fine for users on chrome desktop but failed for chrome android users. We get the response bellow 
result [{"failure":1,"results":[{"error":"MismatchSenderId"}],"success":0,"multicast_id":5148666477777647844,"canonical_ids":0}]

**Comment by addyosmani** [comment]
What version of Chrome for Android is this failing on?

**Comment by jflefebvre06** [comment]
I have added logs to track the user agent
