### ISSUE TITLE
Truncated text

### ISSUE THREAD

**Issue by seanmtracey** [GoogleChrome/push-notifications#35]
![image](https://cloud.githubusercontent.com/assets/913687/23125326/16bc0f3e-f769-11e6-85e4-181bbc7c7a45.png)

When attempting to test the push notifications tutorial with the push companion, the page complains that the subscription endpoint is truncated when it is not.

There are no further error messages.

Version 56.0.2924.87 (64-bit) OS X 10.10.5

**Comment by seanmtracey** [comment]
I think [this line](https://github.com/GoogleChrome/push-notifications/blob/master/companion-site/static/scripts/send-message.js#L47) should be `if (subscriptionObject.endpoint.indexOf('...') > -1) {`

**Comment by gauntface** [comment]
Sorry - was a rushed PR - should be fixed shortly - in the process of deploying now.

**Comment by seanmtracey** [comment]
👍 I've made that mistake too :)
