### ISSUE TITLE
Misleading Screenshot in CodeLab Exercise

### ISSUE THREAD

**Issue by katcaola** [GoogleChrome/push-notifications#37]
As mentioned by @Gekctek in Issue #31, there is a screen shot in the  CodeLab that shows having the `[] ByPass for Network` button checked, as seen [here](https://codelabs.developers.google.com/codelabs/push-notifications/img/d670cb813f3a7575.png) on [the bottom of page 2 of the Code Lab](https://codelabs.developers.google.com/codelabs/push-notifications/index.html?index=..%2F..%2Findex#1). 

The box should be unchecked and there should be a new screenshot with the box unchecked. If the box remains checked, users get a `Failed to subscribe the user:  DOMException: Registration failed - permission denied` error.

**Comment by gauntface** [comment]
Just pushed screenshots to github so others can PR changes (This will require a manual tweak from me or someone who has access to the Google Doc that powers the codelab but it'll speed things up in the future)

Also published new version of the codelab here: https://codelabs.developers.google.com/codelabs/push-notifications/#0

Will chase up how to get these changes pushed to developers.google.com/web/
