### ISSUE TITLE
Not Enabled Push Notification Button in Tab

### ISSUE THREAD

**Issue by arnabmunshi** [GoogleChrome/push-notifications#39]
![17548728_1176313205799662_1523089441_o](https://cloud.githubusercontent.com/assets/4268709/24326560/9929b80e-11d6-11e7-9ee3-ca4e9b37a050.jpg)
![17548961_1176313219132994_462455896_o](https://cloud.githubusercontent.com/assets/4268709/24326561/9a234d06-11d6-11e7-94c6-f1104ee8b3b6.jpg)

**Comment by gauntface** [comment]
@arnabmunshi Can you please explain the issue.

**Comment by arnabmunshi** [comment]
@gauntface Thank you for replying. Actually I'm using my IPv4 address instead of localhost to check in my tab and I'm using XAMPP server. The page opens finely but not the button is not enabled. For this I have posted this issue. But later on I came to know that it is built only for HTTPS connections.

**Comment by gauntface** [comment]
Yes, service workers only work on sites served over HTTPS.

To test on mobile you can use chrome remote debugging. https://developers.google.com/web/tools/chrome-devtools/remote-debugging/

Going to close this issue as it's not a problem with the code lab - please reopen if you disagree.

**Comment by arnabmunshi** [comment]
@gauntface thanks for replying back.
