### ISSUE TITLE
CURL command not working in Step 7

### ISSUE THREAD

**Issue by NickStees** [GoogleChrome/push-notifications#4]
Following the instructions on https://developers.google.com/web/fundamentals/getting-started/push-notifications/step-07?hl=en when I executed the referenced CURL command I was getting just a "to" response in the command line. 

I finally got it working by modifying the CURL to `curl --header "Authorization: key=XXXXXX" --header "Content-Type: application/json" https://gcm-http.googleapis.com/gcm/send -d "{\"to\":\"XXXXXX\"}"`

Is this correct, or was I doing something wrong?

**Comment by strom2357** [comment]
I can't get this to work either using their CURL or your modification -- not sure if it's the same issue or not because I'm getting 401's

**Comment by samdutton** [comment]
Thanks for the reports.

I'm traveling at the moment, but I'll take a look when I get back to the
office.
