### ISSUE TITLE
Images are not appearing on the docs

### ISSUE THREAD

**Issue by thomaspessato** [GoogleChrome/push-notifications#40]
There are some images on the doc that are not appearing.

This is one of them:

https://developers.google.com/web/fundamentals/getting-started/codelabs/push-notifications/img/cb84e05044ad029f.png

Right on the part where we should send the push from the external URL (out from the lab)

This is the URL that has missing images: https://developers.google.com/web/fundamentals/getting-started/codelabs/push-notifications/

**Comment by gauntface** [comment]
Can you possibly provide example text where the image doesn't load and a screenshot.

Looking at the source for the page, that image isn't linked anywhere and I can't see any broken images.

**Comment by thomaspessato** [comment]
My tutorial is in Portuguese, and I can't find anywhere to change it to english, even thought the left menu is in english.

The images are right after the "function updateBtn()" declaration.

This is the screenshot.

![sem titulo](https://cloud.githubusercontent.com/assets/9112010/24913235/e75dc9b6-1ea6-11e7-9bad-57983088f50f.png)

**Comment by gauntface** [comment]
Ah, that helped a lot, thanks for the extra info.

If you scroll right to the bottom of the page, you'll see a toggle switch in the bottom left hand side of the footer where you can change language.

**Comment by gauntface** [comment]
I've raised an issue with Web fundamentals to see what the issue is: https://github.com/google/WebFundamentals/issues/4404
