### ISSUE TITLE
Option to record received notifications on browser

### ISSUE THREAD

**Issue by Xavi007** [GoogleChrome/push-notifications#44]
Most of the web Apps are pushing multiple notification in small intervals; if one opens browser after a some period, We get multiple notification and it's very difficult and time consuming to go through each one of them. There should be an option to record notification in a bookmark on receive event so that they can be read later.

**Comment by gauntface** [comment]
It's not that web apps are sending notifications in "small intervals" but rather if the browser is closed, you'll get all push messages that was sent while the browser was closed.

Regarding your feature request, this is the wrong place to raise this concern.

It might be best to raise an issue: https://github.com/w3c/push-api/issues
