### ISSUE TITLE
Link to WebPush Protocol points to expired document

### ISSUE THREAD

**Issue by efexen** [GoogleChrome/push-notifications#5]
Hey :wave:

Going through the: *Web Fundamentals* - *Getting Started* - *Your first push notifications web app*, codelab/tutorial/guide thing and noticed that on step 4 "Make a project on the Google Developers Console" the link to the Web Push Protocol points to:

https://datatracker.ietf.org/doc/draft-thomson-webpush-protocol/

This appears to be of status **expired and archived** and could cause confusion, I believe:

https://datatracker.ietf.org/doc/draft-ietf-webpush-protocol/

is the current actively worked version.

Apologies for opening the issue here in case it's not the right location to report this, couldn't find the docs themselves here in Github.

Thanks,
.FxN

ps. great work on the guide so far, not looked at any of these before and so far it's been really easy to follow and clear :+1:

**Comment by samdutton** [comment]
Thanks! 

Fixed in google/WebFundamentals#2790. May take a day or two to get published.

(Been traveling and at events — hence the delay in sorting this.)
