### ISSUE TITLE
Any update guide to using FCM since GCM is phasing out? 

### ISSUE THREAD

**Issue by jasan-s** [GoogleChrome/push-notifications#6]

**Comment by mrmcpowned** [comment]
It's been a month this was filed, and since GCM is indeed being phased out in favor of FCM, it would be appreciated if the code lab were updated to reflect this, as there is a fair amount of confusion in setting up the codelab when using FCM instead of GCM.

**Comment by PunKeel** [comment]
+1 Would love help on this one, as I don't understand how FCM allows me to push data to a web worker.. :(

**Comment by MrHubble** [comment]
I'm getting `DOMException: Registration failed - permission denied` errors when following the guide (as described here http://stackoverflow.com/questions/38783357/google-push-notifications-domexception-registration-failed-permission-denie) and it's been difficult to debug (so far I am unsuccessful) and it's also confusing what the involvement of FCM is.

**Comment by gauntface** [comment]
For web push there is no need to worry about which push service is being used by a browser. Web push browsers should return a push service that supports the web push protocol. This protocol defines the API you need to trigger a push message.

I've got a PR out to update this codelab to use the latest web push API: https://github.com/google/WebFundamentals/pull/3841
