### ISSUE TITLE
"This video is private"

### ISSUE THREAD

**Issue by acontal** [GoogleChrome/push-notifications#7]
In step "11. Handle notification clicks", the provided code snippet contains a reference to https://youtu.be/gYMkEMCHtJ4.

Expected outcome: Clicking on the push notification leads to a nice video.
Actual outcome: Clicking on the push notification leads to a "This video is private" error message.

**Comment by gauntface** [comment]
The next version of this codelab won't use this video: https://github.com/google/WebFundamentals/pull/3841
