### ISSUE TITLE
Codelab must be updated to the new version of GCM console

### ISSUE THREAD

**Issue by juarezpaf** [GoogleChrome/push-notifications#9]
Hi y'all... We were trying to use this codelab https://codelabs.developers.google.com/codelabs/push-notifications/index.html at Progressive Web Apps Roadshow Sub-Saharan Africa but the GCM console log has changed a lot and the instructions are wrong.
Step 8 using `curl` always returns this error:
`{"multicast_id":8288173565418041385,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"MismatchSenderId"}]}`

Better yet it would be amazing see updated to use FCM 🔥

**Comment by gauntface** [comment]
The codelab will be updated with the latest web push spec changes soon.
